In [1]:
import numpy as np

In [2]:
np.newaxis

In [15]:
x = np.random.random(10)
x, x.T

(array([0.86471944, 0.3184097 , 0.27756272, 0.69827345, 0.04536768,
        0.36765272, 0.13531974, 0.43579037, 0.09734465, 0.49666414]),
 array([0.86471944, 0.3184097 , 0.27756272, 0.69827345, 0.04536768,
        0.36765272, 0.13531974, 0.43579037, 0.09734465, 0.49666414]))

In [16]:
x[np.newaxis].T

array([[0.86471944],
       [0.3184097 ],
       [0.27756272],
       [0.69827345],
       [0.04536768],
       [0.36765272],
       [0.13531974],
       [0.43579037],
       [0.09734465],
       [0.49666414]])

In [17]:
x

array([0.86471944, 0.3184097 , 0.27756272, 0.69827345, 0.04536768,
       0.36765272, 0.13531974, 0.43579037, 0.09734465, 0.49666414])