In [ ]:
​

Simple Sampeling

import numpy as np

import matplotlib.pyplot as plt

x = np.arange(0,5,0.01)

yy = x**2

plt.plot(x,yy,label='$y=x^2$')

plt.xlabel('x')

plt.ylabel('y')

plt.legend()

<matplotlib.legend.Legend at 0x7f9b82a1d198>

def y(x):

    return x**2

rand_list_upper = []

rand_list_lower = []

for n in range(500):

    i= np.random.random()*5

    j= np.random.random()*25

    if j < y(i):

        rand_list_lower.append((i,j))

    else :

        rand_list_upper.append((i,j))

rand_list_upper = np.array(rand_list_upper)

rand_list_lower = np.array(rand_list_lower)

plt.plot(x,yy,label='$y=x^2$',linewidth=4)

plt.plot(rand_list_upper[:,0],rand_list_upper[:,1],'8g',alpha=0.6,label='The simple samples')

plt.plot(rand_list_lower[:,0],rand_list_lower[:,1],'8b',alpha=0.6,label='The simple samples')

plt.legend()

plt.xlabel('x')

plt.ylabel('y')

Text(0, 0.5, 'y')

counter=0

N =1000

integral = []

for many_values in range(50):

    counter=0

    for i in range(N):

        rand_x = np.random.random()*5

        rand_y = np.random.random()*25

        if rand_y<y(rand_x):

              counter+=1

    integral.append(counter/1000 * 25*5)

print('the result of integral is :{}'.format(counter/1000 * 25*5))

print("The Real Value of the integral is :{}".format(125/3))

the result of integral is :42.0
The Real Value of the integral is :41.666666666666664

mean = np.array(integral).mean()

​

plt.plot(integral)

plt.plot(integral,'8',label='Values of integral')

plt.plot([mean for i in range(len(integral))],label='Mean = {}'.format(mean))

plt.plot([41.66 for i in range(len(integral))],label='Real Value=%3.4f'%(125/3))

plt.xlabel('Trials')

plt.ylabel('Value of Integral')

plt.legend()

<matplotlib.legend.Legend at 0x7f9b83458a20>

Better way

line = np.arange(0,5,0.01)

value = 2

predicted_ratio = 2/5

counter=0

N = 5000

N_list = [i**2 for i in range(0,27)]

ratio_values = []

for N in N_list:

    counter =0

    for i in range(N):

        rand  = np.random.random()*5

        if rand<value:

            counter+=1

    ratio_values.append((N,counter/(N+1)))

​

ratio_values = np.array(ratio_values)

plt.plot(ratio_values[:,0],ratio_values[:,1],label='Predicted Ratio')

plt.plot(ratio_values[:,0],ratio_values[:,1],'8')

plt.plot([2/5 for i in range(int(ratio_values[:,0][-1]))],label='Ratio={}'.format(2/5))

plt.legend()

plt.xlabel('number of samples')

plt.ylabel('Ratio')

Text(0, 0.5, 'Ratio')

rand = np.random.random(1000) * 5

plt.plot(x,yy,label='$y=x^2$',linewidth=4)

plt.hist(rand,bins=40,label = 'Distribution of the Simple Samples',alpha = 0.8)

plt.xlabel('x')

plt.ylabel('y')

plt.legend()

<matplotlib.legend.Legend at 0x7f3e3ba5bda0>

counter=0

N =10000

integral = []

for many_values in range(50):

    counter=0

    for i in range(N):

        rand_x = np.random.random()*5

        counter+=y(rand_x)/25

    integral.append(counter/N * 25*5)

mean = np.array(integral).mean()

plt.plot(integral)

plt.plot(integral,'8',label="Calculated values")

plt.plot([mean for i in range(len(integral))],label='Mean=%3.4f'%(mean))

plt.plot([125/3 for i in range(len(integral))],label='Real Value=%3.4f'%(125/3))

plt.xlabel('trials')

plt.ylabel('Integral Value')

plt.title('Integral of $y=x^2$')

plt.legend()

<matplotlib.legend.Legend at 0x7f9b824d0518>

Simple sampeling for Guassian

def Guassian(x,std,mean):

    return 1/(2*np.pi*std**2)**0.5 * np.exp(-(x-mean)**2/(2*std**2))

x = np.arange(-5,5,0.01)

y = Guassian(x,1,0)

plt.plot(x,y,label='Guassian')

plt.xlabel('x')

plt.ylabel('y')

plt.legend()

<matplotlib.legend.Legend at 0x7f9b82c5cf60>

upper_samples = []

lower_samples = []

for N in range(900):

    i = np.random.random()*8 -4

    j = np.random.random()*Guassian_0

    if j<Guassian(i,1,0):

        lower_samples.append((i,j))

    else:

        upper_samples.append((i,j))

lower_samples = np.array(lower_samples)

upper_samples = np.array(upper_samples)

plt.plot(x,y,'b',linewidth=6,label="Guassian")

plt.xlim([-4,4])

plt.plot(upper_samples[:,0],upper_samples[:,1],'8g',alpha=0.5,label='Simple Samples')

plt.plot(lower_samples[:,0],lower_samples[:,1],'8b',alpha=0.5,label = "Simple Samples")

plt.legend()

plt.xlabel('x')

plt.ylabel('y')

Text(0, 0.5, 'y')

Calculaing the integral -4 to +4

N = 100000

Guassian_0 = Guassian(0,1,0)

integral = []

for many_values in range(50):

  counter  = 0

  for sample in range(N):

    rand_x = np.random.random()*8 -4

    rand_y = np.random.random()* Guassian_0

    if rand_y<Guassian(rand_x,1,0):

      counter+=1

  integral.append(counter/N * 8*Guassian_0)

print('the result of integral is :{}'.format(counter/N * 8*Guassian_0))

print("The Real Value of the integral is :{}".format(0.999936658))

​

the result of integral is :1.0014727853373246
The Real Value of the integral is :0.999936658

print('the result of integral is :{}'.format(counter/N * 8*Guassian_0))

print("The Real Value of the integral is :{}".format(0.999936658))

the result of integral is :1.0014727853373246
The Real Value of the integral is :0.999936658

mean = np.array(integral).mean()

plt.plot(integral)

plt.plot(integral,'8',label='Calculated Values')

plt.plot([mean for i in range(len(integral))],label='Mean=%3.4f'%(mean))

plt.plot([0.999936 for i in range(len(integral))],label='The Real Value={}'.format(0.999936))

plt.legend()

<matplotlib.legend.Legend at 0x7f9b82b6ef98>

​

Better way

N = 10000

Guassian_0 = Guassian(0,1,0)

integral = []

for many_values in range(50):

    counter  = 0

    for sample in range(N):

        rand_x = np.random.random()*8 -4

        counter+=Guassian(rand_x,1,0)/Guassian_0

    integral.append(counter/N*8*Guassian_0)

​

print('the result of integral is :{}'.format(integral[1]))

print("The Real Value of the integral is :{}".format(0.999936658))

​

the result of integral is :1.0109200026345588
The Real Value of the integral is :0.999936658

mean = np.array(integral).mean()

plt.plot(integral)

plt.plot(integral,'8',label='Calculated integral')

plt.plot([mean for i in range(len(integral))],label ='Mean=%3.4f'%(mean))

plt.plot([0.999936 for i in range(len(integral))],label='The Real Value={}'.format(0.999936))

plt.xlabel('trails')

plt.ylabel('Integral Value')

plt.title('Integral for Guassian')

plt.legend()

<matplotlib.legend.Legend at 0x7f9b821cb7f0>

​

​

from mpl_toolkits.mplot3d import Axes3D

import matplotlib.pyplot as plt

import numpy as np

​

​

fig = plt.figure()

ax = fig.add_subplot(111, projection='3d')

​

# Make data

u = np.linspace(0, 2 * np.pi, 100)

v = np.linspace(0, np.pi, 100)

x = 1* np.outer(np.cos(u), np.sin(v))

y = 1 * np.outer(np.sin(u), np.sin(v))

z = 1 * np.outer(np.ones(np.size(u)), np.cos(v))

​

# Plot the surface

ax.plot_surface(x, y, z, color='b')

​

plt.show()

def density(z):

    rho = 1

    return rho/4*(z+3)

    #return 1

z_list= []

rho_list = []

for i in range(100):

    r_rand = np.random.random()*2 - 1

    th_rand = np.random.random() *np.pi

    z = r_rand*np.cos(th_rand)

    z_list.append(z)

    rho_list.append(density(z))

plt.plot(z_list)

plt.plot(rho_list)

[<matplotlib.lines.Line2D at 0x7f3e3cb0b320>]

x_coordinates = np.linspace(-1,1,500)

y_coordinates = np.linspace(-1,1,500)

z_coordinates = np.linspace(-1,1,500)

dv = 500**3

CM_values = []

for many_values in range(50):

    Total_mass = 0

    CM=0  

    for sample in range(10000):

        r_rand = np.random.random()*2 - 1

        th_rand = np.random.random() *np.pi

        z = r_rand*np.cos(th_rand)

        dm = dv*density(z)

        Total_mass += dm

        CM += r_rand*np.cos(th_rand)*dm

    CM_values.append(CM/Total_mass)

mean = np.array(CM_values).mean()

mean

0.05461754199585545

plt.plot(CM_values)

plt.plot(CM_values,'8',label = "Calculated Z for CM")

plt.plot([mean for i in range(len(CM_values))],label='Mean =%3.4f'%mean)

plt.xlabel('Trials')

plt.ylabel('Z')

plt.legend()

​

<matplotlib.legend.Legend at 0x7f3e3cab8860>

std= np.array(CM_values).std()

std

0.003976259686057684

Important Sampeling

x = np.arange(0,5,0.01)

yy = y(x)

plt.plot(x,yy)

[<matplotlib.lines.Line2D at 0x7f3e3c7752e8>]

rand = np.random.randn(700)*1.2 + 5

plt.hist(rand,bins=50,label='Distribution of Important Samples',alpha = 0.9)

plt.plot(x,yy,label='$y=x^2$',linewidth=4)

plt.title('Important Samples')

plt.xlim(0,5)

plt.xlabel('x')

plt.ylabel('y')

plt.legend()

<matplotlib.legend.Legend at 0x7f3e3b361f98>

counter=0

N =10000

integral = []

for many_values in range(50):

    counter=0

    for i in range(N):

        rand_x = np.random.random()*5

        counter+=y(rand_x)/25

    integral.append(counter/N * 25*5)

mean = np.array(integral).mean()

plt.plot(integral)

plt.plot(integral,'8',label="Calculated values")

plt.plot([mean for i in range(len(integral))],label='Mean=%3.4f'%(mean))

plt.plot([125/3 for i in range(len(integral))],label='Real Value=%3.4f'%(125/3))

plt.xlabel('trials')

plt.ylabel('Integral Value')

plt.title('Integral of $y=x^2$ using Important Sampling')

plt.legend()

<matplotlib.legend.Legend at 0x7f3e3b126320>

Comparison

def Guassian(x,std,mean):

    return 1/(2*np.pi*std**2)**0.5 * np.exp(-(x-mean)**2/(2*std**2))

x = np.linspace(0,2,1000)

yy  = Guassian(x,1,0)

plt.plot(x,yy)

[<matplotlib.lines.Line2D at 0x7f3e3b0a0d68>]

rand = np.random.random(300)

rand_Guassian = -np.log(rand)

plt.hist(rand_Guassian,bins = 30)

plt.xlim(0,2)

(0, 2)

plt.plot(x,100*yy,linewidth=5,label='Guassian')

plt.hist(rand_Guassian,bins=40,label='distribution of important samples')

plt.xlim(0,2)

plt.title('Important Sampling')

plt.legend()

​

<matplotlib.legend.Legend at 0x7f3e3a9e0278>

rand = np.random.random(500)*2

plt.plot(x,50*yy,linewidth=5,label='Guassian')

plt.hist(rand,bins=40,label='distribution of simple samples')

plt.title('Simple Sampling')

plt.xlim(0,2)

plt.legend()

<matplotlib.legend.Legend at 0x7f3e3a051fd0>

%%time 

N = 10000

Guassian_0 = Guassian(0,1,0)

integral = []

for many_values in range(50):

    counter  = 0

    for sample in range(N):

        rand_x = np.random.random()*2

        counter+=Guassian(rand_x,1,0)/Guassian_0

    integral.append(counter/N*2*Guassian_0)

​

CPU times: user 1.38 s, sys: 0 ns, total: 1.38 s
Wall time: 1.38 s

plt.plot(integral)

[<matplotlib.lines.Line2D at 0x7f3e39ed55c0>]

​

​

TESTS

rand = np.random.randn(1000)

n,bins,ignore = plt.hist(rand,bins=2)

n

array([601., 399.])

binns = bins.copy()

bins[1]=4

bins, binns

(array([-2.67737251,  4.        ,  3.25768246]),
 array([-2.67737251,  4.        ,  3.25768246]))

for i in range(bins.shape[0]):

    binss

