In [219]:
import numpy as np
import matplotlib.pyplot as plt

In [220]:
def surface_generator(surface,L,t):  
    place_list = [i for i in range(L)]
    for i in range(t):
        
        rand = int(np.random.choice(place_list,1))

        
        if rand == 0:
            if surface[rand+1][-1][1]>surface[rand][-1][1]:
                surface[rand].append((rand, surface[rand-1][-1][1]))
            elif surface[L-1][-1][1]>surface[rand][-1][1]:
                surface[rand].append((rand, surface[L-1][-1][1]))
            else:
                surface[rand].append((rand, surface[rand][-1][1]+1))
                
        elif rand == L-1:
            if surface[rand-1][-1][1] > surface[rand][-1][1]:
                surface[rand].append((rand, surface[rand-1][-1][1]))
            elif surface[0][-1][1] > surface[rand][-1][1]:
                surface[rand].append((rand, surface[0][-1][1]))
            else:
                surface[rand].append((rand, surface[rand][-1][1]+1))

        else:
            
            
            if surface[rand+1][-1][1] > surface[rand][-1][1]:
                surface[rand].append((rand, surface[rand+1][-1][1]))
                
            
            elif surface[rand-1][-1][1]> surface[rand][-1][1]:
                surface[rand].append((rand, surface[rand-1][-1][1]))
                
            else:
                surface[rand].append((rand, surface[rand][-1][1]+1))
    plot_points = []
    for place in surface:
        plot_points+=place
    return np.array(plot_points), surface

In [221]:
def surface_points_extractors(data):
    height_of_surface  =[]
    for i in range(L):
        height_of_surface.append(data[data[:,0]==i][-1][1])
    return np.array(height_of_surface)

# Surface

In [222]:
L=500
surface = [ [] for i in range(L)]
i=0
for place in surface:
    place.append((i,0))
    i+=1
data, array = surface_generator(surface,L,30000) 
#data2 = surface_generator(array,L,25000)

In [223]:
data[:,0]

array([  0,   0,   0, ..., 499, 499, 499])

In [224]:
plt.figure(figsize=(10,10))
plt.plot(data[:,0], data[:,1],'.')
#plt.plot(data2[:,0], data2[:,1],'r.')

In [225]:
surface = surface_points_extractors(data)

In [226]:
surface.std()

5.196436856154417

In [227]:
L=300
surface = [ [] for i in range(L)]
i=0
for place in surface:
    place.append((i,1))
    i+=1
surface[int(L/2)].append((int(L/2), 50))

In [228]:
data,poin = surface_generator(surface,L,19100)

In [229]:
data[50]

array([ 0, 60])

In [230]:
plt.figure(figsize=(10,10))
plt.plot(data[:,0], data[:,1],'s', markersize=2)

In [231]:
data = surface_points_extractors(data)

In [232]:
surface

[[(0, 1),
  (0, 2),
  (0, 6),
  (0, 7),
  (0, 8),
  (0, 9),
  (0, 10),
  (0, 11),
  (0, 11),
  (0, 12),
  (0, 12),
  (0, 17),
  (0, 20),
  (0, 21),
  (0, 22),
  (0, 23),
  (0, 25),
  (0, 25),
  (0, 25),
  (0, 32),
  (0, 33),
  (0, 34),
  (0, 36),
  (0, 36),
  (0, 36),
  (0, 38),
  (0, 39),
  (0, 40),
  (0, 40),
  (0, 40),
  (0, 41),
  (0, 41),
  (0, 41),
  (0, 41),
  (0, 42),
  (0, 45),
  (0, 49),
  (0, 49),
  (0, 50),
  (0, 51),
  (0, 52),
  (0, 52),
  (0, 58),
  (0, 59),
  (0, 59),
  (0, 60),
  (0, 60),
  (0, 60),
  (0, 60),
  (0, 60),
  (0, 60),
  (0, 65),
  (0, 66),
  (0, 67),
  (0, 67),
  (0, 88),
  (0, 90),
  (0, 90),
  (0, 102),
  (0, 103),
  (0, 104),
  (0, 103),
  (0, 103)],
 [(1, 1),
  (1, 2),
  (1, 3),
  (1, 7),
  (1, 9),
  (1, 10),
  (1, 11),
  (1, 12),
  (1, 13),
  (1, 14),
  (1, 15),
  (1, 16),
  (1, 17),
  (1, 18),
  (1, 19),
  (1, 20),
  (1, 22),
  (1, 26),
  (1, 27),
  (1, 28),
  (1, 29),
  (1, 30),
  (1, 31),
  (1, 36),
  (1, 37),
  (1, 38),
  (1, 39),
  (1, 40),
  (1

In [233]:
data

array([103, 130, 128, 131, 131, 130, 128, 128, 129, 127, 132, 132, 130,
       130, 128, 133, 132, 130, 130, 132, 127, 127, 127, 124, 126, 128,
       124, 125, 124, 116, 119, 117, 113, 128, 121, 121, 122, 120, 120,
       116, 116, 116, 117, 117, 117, 119, 119, 121, 119, 122, 123, 120,
       121, 120, 124, 112, 123, 123, 128, 128, 128, 130, 121, 125, 128,
       126, 126, 125, 129, 128, 128, 128, 129, 122, 123, 123, 123, 118,
       123, 123, 124, 116, 118, 119, 119, 109, 149, 157, 157, 156, 158,
       157, 158, 149, 155, 154, 160, 160, 164, 165, 162, 163, 164, 163,
       162, 162, 160, 162, 162, 162, 170, 170, 170, 169, 167, 167, 170,
       170, 168, 169, 169, 168, 179, 179, 179, 176, 177, 180, 180, 179,
       179, 180, 179, 171, 173, 173, 173, 174, 173, 172, 174, 173, 174,
       172, 163, 172, 169, 170, 169, 176, 173, 177, 177, 173, 173, 174,
       174, 174, 171, 171, 174, 173, 162, 164, 163, 164, 163, 153, 155,
       154, 157, 158, 156, 157, 156, 148, 148, 148, 112, 114, 11

In [237]:
L =180
surface_arr = [[] for i in range(L)]
i=0
for place in surface_arr:
    place.append((i,0))
    i+=1
    

In [238]:
release_list = [2**i for i in range(2,20)]

In [239]:
std_list = []
N_total = 0
for release in release_list:
    N_total+=release
    points, surface_arr = surface_generator(surface_arr, L, release)
    std_list.append((N_total,surface_points_extractors(points).std()))
    print(np.log2(release))
std_list = np.array(std_list)

2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0


In [ ]:
plt.loglog(std_list[:,0], std_list[:,1],'8')

In [ ]:
plt.loglog(std_list[:,0], std_list[:,1],'8', label = '')
plt.xlabel('t')
plt.ylabel('w')

In [ ]:
plt.figure(figsize=(25,18))
plt.plot(points[:,0], points[:,1],',')


In [ ]:
plt.plot(points[:,0], points[:,1],'o')

In [ ]:
plt.plot(points[:,0], points[:,1],'o')

In [ ]:
plt.plot

In [ ]:
change(a)

In [ ]:
a

In [ ]:
np.random.choice([1,2,3],4)